language: ruby
rvm:
  - 1.9.3
  - 1.9.2
  - ruby-head
  - jruby-19mode
  - jruby-head
  - rbx-19mode

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

notifications:
  irc: "irc.freenode.org#mongrel2-ruby"

before_install:
  - sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:pawelpacana/xUbuntu_12.04/ /' >> /etc/apt/sources.list"
  - wget -q -O - http://download.opensuse.org/repositories/home:pawelpacana/xUbuntu_12.04/Release.key | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install -qq mongrel2
