language: ruby
rvm:
  - 1.9.3
  - 1.9.2
  - ruby-head
  - jruby-19mode
  - jruby-head
  - rbx-19mode

matrix:
  allow_failures:
    - rvm: ruby-head

notifications:
  irc: "irc.freenode.org#mongrel2-ruby"
