language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0-preview1
  - jruby-19mode
  - rbx-19mode

env:
  - PATH=/opt/mongrel2-1.8.1/bin:$PATH

notifications:
  irc: "irc.freenode.org#mongrel2-ruby"

before_install:
  - sudo apt-get install -qq libzmq3-dev
  - mkdir mongrel2-1.8.1
  - curl -L https://github.com/zedshaw/mongrel2/archive/v1.8.1.tar.gz -o - |tar --strip-components=1 -C mongrel2-1.8.1 -zxvf -
  - pushd mongrel2-1.8.1
  - make PREFIX=/opt/mongrel2-1.8.1
  - sudo make install PREFIX=/opt/mongrel2-1.8.1
  - popd

script: bundle exec rake
