language: ruby
rvm:
  - 1.9.3
  - 1.9.2
  - ruby-head
  - jruby-19mode
  - jruby-head
  - rbx-19mode

env:
  - PATH=/opt/mongrel2-1.7.5/bin:$PATH
  - PATH=/opt/mongrel2-1.8.1/bin:$PATH

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

notifications:
  irc: "irc.freenode.org#mongrel2-ruby"

before_install:
  - mkdir mongrel2-1.7.5
  - curl -L https://github.com/zedshaw/mongrel2/archive/v1.7.5.tar.gz -o - |tar --strip-components=1 -C mongrel2-1.7.5 -zxvf -
  - cd mongrel2-1.7.5
  - make PREFIX=/opt/mongrel2-1.7.5
  - sudo make install PREFIX=/opt/mongrel2-1.7.5
  - cd ..
  - mkdir mongrel2-1.8.1
  - curl -L https://github.com/zedshaw/mongrel2/archive/v1.8.1.tar.gz -o - |tar --strip-components=1 -C mongrel2-1.8.1 -zxvf -
  - cd mongrel2-1.8.1
  - make PREFIX=/opt/mongrel2-1.8.1
  - sudo make install PREFIX=/opt/mongrel2-1.8.1

