language: ruby
rvm:
  - 1.9.3
  - 1.9.2
  - ruby-head
  - jruby-19mode
  - jruby-head
  - rbx-19mode

before_install:
  - sudo add-apt-repository -y ppa:mongrel2/release
  - sudo apt-get update -qq
  - sudo apt-get install -qq mongrel2

matrix:
  allow_failures:
    - rvm: ruby-head

notifications:
  irc: "irc.freenode.org#mongrel2-ruby"
