language: ruby
rvm:
  - 1.9.3
  - 1.9.2
  - ruby-head
  - jruby-19mode
  - jruby-head
  - rbx-19mode

env:
  - PATH=/opt/mongrel2-1.7.5/bin:$PATH
  - PATH=/opt/mongrel2-1.8.0/bin:$PATH

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

notifications:
  irc: "irc.freenode.org#mongrel2-ruby"

before_install:
  - curl -o - https://raw.github.com/gist/3690228/329913ac81c8749dadcc08e220a62c33a8a51897/make_everything_ok.sh | sh
